const BLACK_COLOR = '#000000'
const WHITE_COLOR = '#ffffff'
const FIRST_HEADING_COLOR = '#ff4430'
const SECOND_HEADING_COLOR = '#917164'
const THIRD_HEADING_COLOR = '#68fcf4'
const EMPHASIS_COLOR = '#689775'
export {
    BLACK_COLOR,
    WHITE_COLOR,
    FIRST_HEADING_COLOR,
    SECOND_HEADING_COLOR,
    THIRD_HEADING_COLOR,
    EMPHASIS_COLOR,
}
