const TRANSITION = '1.5s'
const NAME_DELAY = 1
const BTN_DELAY = NAME_DELAY + 1
const ICON_SIZE = 40
const DOUBLE_UNDERSCORE_REGEX = /__(.*?)__/g

export { TRANSITION, NAME_DELAY, BTN_DELAY, ICON_SIZE, DOUBLE_UNDERSCORE_REGEX }
