name: Build and Deploy
on:
    push:
        branches: [main]
jobs:
    install:
        name: Install Dependencies
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: install node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: install npm packages
              run: npm install
    test:
        name: Run Tests
        needs: install
        runs-on: ubuntu-latest
        steps:
            - name: list files
              run: ls -al
            - name: test project
              run: npm run test
    build:
        name: Run Build
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: build project
              run: npm run build
            - name: upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: production-files
                  path: dist
    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: download artifact
              uses: actions/download-artifact@v3
              with:
                  name: production-files
                  path: dist
            - name: deploy to gh-pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: dist
